### ISSUE TITLE
Detect page enter and leave

### ISSUE THREAD

**Issue by sunilson** [inloop/UpdatableFragmentStatePagerAdapter#6]
Is there any way that the fragments inside the adapter can detect when they are shown/hidden?

**Comment by VladTE** [comment]
Hi @sunilson ! Have you tried overriding the method "setMenuVisibility(boolean menuVisible)" inside your fragments?

**Comment by sunilson** [comment]
Hi, I didn't know about that method, I think this does what I want. Thanks!
